Repository portiaAI/portia-sdk-python, pull requests merged in 2025-07, with the labels that each got.

#551 Release v0.4.8
  pyproject.toml
Labels: ready_to_eval, release

#553 ph banner and cool badges
  .DS_Store
  README.md
  assets/ph_banner.jpg
Labels: ready_to_eval

#555 uv lock --upgrade
  uv.lock
Labels: ready_to_eval

#557 Fixing the default config to be ONE_SHOT agent
  portia/config.py
  portia/portia.py
  tests/unit/test_config.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#558 Release v0.4.9
  pyproject.toml
Labels: ready_to_eval, release

#562 Remove DS_Store file and add it in gitignore
  .DS_Store
  .gitignore
Labels: ready_to_eval

#560 Fix daily tests
  .github/workflows/daily-tests.yml
  tests/integration/open_source_tools/test_browser_tool.py
Labels: ready_to_eval

#518 Browser Tool Dependency updates
  .gitignore
  portia/open_source_tools/browser_tool.py
  pyproject.toml
  tests/unit/open_source_tools/test_browser_tool.py
  uv.lock
Labels: ready_to_eval

#567 Include version in telemetry
  portia/cli.py
  portia/portia.py
  portia/telemetry/telemetry_service.py
  portia/version.py
  tests/unit/telemetry/test_telemetry_service.py
  tests/unit/test_version.py
Labels: ready_to_eval

#569 Release v0.4.10
  pyproject.toml
Labels: release

#570 fix for browser-use
  portia/model.py
  portia/open_source_tools/browser_tool.py
  tests/unit/open_source_tools/test_browser_tool.py
  uv.lock
Labels: ready_to_eval

#572 [POR-1685] Added a fix for anthropic warnings
  portia/config.py
  portia/model.py
  tests/unit/test_model.py
  uv.lock
Labels: ready_to_eval

#543 Fixing clarifications and step summarisation for step unrolling cases
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/execution_utils.py
  portia/execution_agents/one_shot_agent.py
  portia/execution_agents/utils/step_summarizer.py
  portia/open_source_tools/llm_tool.py
  portia/portia.py
  tests/unit/execution_agents/test_execution_utils.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
  uv.lock
Labels: ready_to_eval

#579 Fix SDK docs for tool descriptions
  portia/tool_registry.py
Labels: ready_to_eval

#578 Log the stack trace when exiting plan run with error
  portia/logger.py
  portia/portia.py
  portia/tool_decorator.py
  tests/unit/test_logging.py
  tests/unit/test_tool_decorator.py
Labels: ready_to_eval

#581 [POR-1686] Fixing python version errors by specifying python versions per dependency
  pyproject.toml
  uv.lock
Labels: ready_to_eval

#584 Update README.md
  README.md
Labels: ready_to_eval

#510 Add Tool run signature validator
  portia/tool.py
  tests/unit/test_tool.py
Labels: ready_to_eval, codex

#582 Encourage use of calculator tool vs LLM tool
  portia/open_source_tools/calculator_tool.py
  portia/open_source_tools/llm_tool.py
Labels: ready_to_eval

#586 staging updater
  .github/workflows/trigger-downstream-updates.yml
Labels: ready_to_eval

#588 Bugfix: raise ToolSoftError when LLM introduces templated variables not in step inputs
  portia/execution_agents/execution_utils.py
  tests/unit/execution_agents/test_execution_utils.py
Labels: ready_to_eval

#592 Upgrade langchain-genai and minor planning prompt improvement
  portia/templates/default_planning_agent.xml.jinja
  pyproject.toml
  uv.lock
Labels: ready_to_eval

#587 Browseruse fixes for local infra option
  portia/open_source_tools/browser_tool.py
  pyproject.toml
  tests/unit/open_source_tools/test_browser_tool.py
  uv.lock
Labels: ready_to_eval

#597 Fix fstring
  portia/execution_hooks.py
Labels: ready_to_eval

#604 Fix typing of example plans
  portia/portia.py
Labels: ready_to_eval

#605 trigger platform
  .github/workflows/ready_to_eval_labeller.yml
  .github/workflows/trigger-downstream-updates.yml
Labels: ready_to_eval

#601 Async portia planning
  portia/model.py
  portia/planning_agents/base_planning_agent.py
  portia/planning_agents/default_planning_agent.py
  portia/portia.py
  pyproject.toml
  tests/integration/test_e2e.py
  tests/integration/test_model.py
  tests/unit/planning_agents/test_default_planning_agent.py
  tests/unit/telemetry/test_telemetry_service.py
  tests/unit/test_model.py
  tests/unit/test_portia.py
  tests/utils.py
  uv.lock
Labels: ready_to_eval

#609 Portia logo broken on pypi
  README.md
Labels: ready_to_eval

#612 Adjust planning prompt
  portia/planning_agents/default_planning_agent.py
Labels: ready_to_eval

#616 async step-summarizer
  portia/execution_agents/utils/step_summarizer.py
  portia/tool.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
Labels: ready_to_eval

#618 async introspection
  .cursor/rules/sdk-context.mdc
  portia/introspection_agents/default_introspection_agent.py
  portia/introspection_agents/introspection_agent.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
Labels: ready_to_eval

#619 Execute plan run refactor
  portia/errors.py
  portia/portia.py
  tests/unit/test_portia.py
  uv.lock
Labels: ready_to_eval

#615 Improve gemini planning and switch to gemini evals
  .github/workflows/evals.yml
  portia/open_source_tools/llm_tool.py
  portia/planning_agents/context.py
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  portia/templates/example_plans.py
  tests/unit/planning_agents/test_default_planning_agent.py
Labels: ready_to_eval

#625 Test cleanup
  tests/unit/conftest.py
  tests/unit/test_portia.py
  tests/unit/test_portia_async.py
Labels: ready_to_eval
