Repository portiaAI/portia-sdk-python, pull requests merged in 2025-05, with the labels that each got.

#367 Add Bandit in CI
  .github/workflows/security.yml
  portia/open_source_tools/calculator_tool.py
  tests/unit/open_source_tools/test_calculator_tool.py
Labels: ready_to_eval

#369 Add ability for execution agent to template large outputs
  portia/execution_agents/default_execution_agent.py
  tests/integration/data/war_and_peace_ch1.txt
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_default_execution_agent.py
Labels: ready_to_eval

#372 Remove branch check
  .github/workflows/branch_checks.yml
Labels: ready_to_eval

#375 Rename LocalOutput, AgentMemoryOutput -> LocalDataValue, AgentMemoryValue
  portia/execution_agents/execution_utils.py
  portia/execution_agents/memory_extraction.py
  portia/execution_agents/output.py
  portia/introspection_agents/default_introspection_agent.py
  portia/portia.py
  portia/storage.py
  portia/tool.py
  portia/tool_wrapper.py
  tests/integration/test_execution_agent.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_context.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/test_execution_utils.py
  tests/unit/execution_agents/test_memory_extraction.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/execution_agents/test_output.py
  tests/unit/execution_agents/utils/test_final_output_summarizer.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/test_plan_run.py
  tests/unit/test_portia.py
  tests/unit/test_storage.py
  tests/unit/test_tool_wrapper.py
  tests/utils.py
Labels: ready_to_eval

#376 remove unnecessary typing
  portia/execution_agents/execution_utils.py
  portia/execution_agents/output.py
  portia/introspection_agents/introspection_agent.py
  portia/tool.py
Labels: ready_to_eval

#378 Execution agent prompt engineering
  portia/execution_agents/default_execution_agent.py
Labels: ready_to_eval

#355 Add plan inputs
  .cursor/rules
  example.py
  portia/__init__.py
  portia/execution_agents/memory_extraction.py
  portia/execution_agents/output.py
  portia/introspection_agents/default_introspection_agent.py
  portia/plan.py
  portia/plan_run.py
  portia/planning_agents/base_planning_agent.py
  portia/planning_agents/context.py
  portia/planning_agents/default_planning_agent.py
  portia/portia.py
  portia/storage.py
  portia/templates/default_planning_agent.xml.jinja
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_memory_extraction.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/planning_agents/test_default_planning_agent.py
  tests/unit/test_plan.py
  tests/unit/test_plan_run.py
  tests/unit/test_portia.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#379 Merge on save
  portia/storage.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#381 Sort cursor files
  .cursor/context.md
Labels: ready_to_eval

#380 Update PlanInput to not require a LocalDataValue
  portia/planning_agents/default_planning_agent.py
  portia/portia.py
  portia/templates/default_planning_agent.xml.jinja
  tests/integration/test_e2e.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#373 llmtool via oneshot
  portia/portia.py
Labels: ready_to_eval

#384 Allow running a plan by ID
  portia/__init__.py
  portia/portia.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#388 Release v0.3.2
  pyproject.toml
Labels: ready_to_eval, release

#390 Update README
  README.md
Labels: ready_to_eval

#392 Release v0.3.3
  pyproject.toml
Labels: release

#383 Add execution hooks
  portia/cli_clarification_handler.py
  portia/execution_agents/base_execution_agent.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/execution_utils.py
  portia/execution_agents/one_shot_agent.py
  portia/execution_hooks.py
  portia/portia.py
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/test_execution_utils.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/test_execution_hooks.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#397 Evals improvements
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  portia/templates/example_plans.py
Labels: ready_to_eval

#396 Update star GIF and minor tidy up
  README.md
  portia/__init__.py
Labels: ready_to_eval

#385 Agent memory dogfooding
  portia/execution_agents/default_execution_agent.py
  portia/portia.py
  portia/storage.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#398 LLM tool tweak
  portia/open_source_tools/llm_tool.py
Labels: ready_to_eval

#399 Turn on agent memory feature flag by default
  portia/config.py
Labels: ready_to_eval

#401 [RUN-48] Pin browser-use version
  poetry.lock
  pyproject.toml
Labels: ready_to_eval

#402 Sort async clarification handling
  portia/portia.py
Labels: ready_to_eval

#407 Updates from plan input dogfooding
  example.py
  portia/__init__.py
  portia/introspection_agents/default_introspection_agent.py
  portia/plan.py
  portia/planning_agents/default_planning_agent.py
  portia/portia.py
  portia/storage.py
  portia/templates/default_planning_agent.xml.jinja
  tests/integration/test_e2e.py
  tests/unit/planning_agents/test_default_planning_agent.py
  tests/unit/test_plan.py
  tests/unit/test_portia.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#409 Add Portia API endpoint log line
  portia/portia.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#410 Put one-shot agent clarifications behind feature flag
  portia/config.py
  portia/execution_agents/one_shot_agent.py
  tests/unit/execution_agents/test_oneshot_agent.py
Labels: ready_to_eval

#412 Sort pre commit
  .pre-commit-config.yaml
Labels: ready_to_eval

#413 [RUN-44] Update llm_tool to handle variaty of inputs to make use of memory agent
  portia/open_source_tools/llm_tool.py
  tests/unit/open_source_tools/test_llm_tool.py
Labels: ready_to_eval

#414 Release v0.3.4
  pyproject.toml
Labels: release

#403 Add step check to before_first_step_execution
  portia/portia.py
Labels: ready_to_eval

#415 Plan input bug fix
  .github/workflows/evals.yml
  portia/execution_agents/default_execution_agent.py
  portia/plan.py
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  tests/integration/test_e2e.py
Labels: ready_to_eval

#417 Add browser tool log line to easily get debug link
  portia/open_source_tools/browser_tool.py
Labels: ready_to_eval

#419 Add remove additional data
  portia/end_user.py
  portia/open_source_tools/browser_tool.py
  tests/unit/test_end_user.py
Labels: ready_to_eval

#416 Prevent logging errors
  portia/logger.py
  portia/tool_wrapper.py
  tests/unit/test_logging.py
Labels: ready_to_eval

#421 Tighten language in browser tool prompt
  portia/open_source_tools/browser_tool.py
Labels: ready_to_eval

#424 Fix browser tool session management
  portia/open_source_tools/browser_tool.py
  tests/unit/open_source_tools/test_browser_tool.py
Labels: ready_to_eval

#425 Release v0.3.5
  pyproject.toml
Labels: release

#423 Only show end-user info to planning agent if it exists
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
Labels: ready_to_eval

#426 Run SDK evals on merge
  .github/workflows/evals.yml
Labels: ready_to_eval

#427 migration to UV
  .cursor/context.md
  .github/workflows/create-release-pr.yml
  .github/workflows/create-release-tag.yml
  .github/workflows/deploy_pypi.yml
  .github/workflows/evals.yml
  .github/workflows/licence.yml
  .github/workflows/pyright.yml
  .github/workflows/release.yml
  .github/workflows/security.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  poetry.lock
  portia/clarification.py
  portia/clarification_handler.py
  portia/cli.py
  portia/cli_clarification_handler.py
  portia/config.py
  portia/execution_agents/context.py
  portia/execution_agents/output.py
  portia/execution_hooks.py
  portia/tool_registry.py
  pyproject.toml
  tests/integration/test_e2e.py
  tests/integration/test_mcp_session.py
  tests/unit/open_source_tools/test_llm_tool.py
  tests/unit/test_plan.py
  tests/unit/test_tool_registry.py
  tests/utils.py
  uv.lock
Labels: ready_to_eval

#428 Release v0.3.6-alpha
  pyproject.toml
Labels: ready_to_eval, release

#429 Action fix
  .github/workflows/create-release-pr.yml
  .github/workflows/create-release-tag.yml
  .github/workflows/deploy_pypi.yml
  uv.lock
Labels: ready_to_eval

#430 Release v0.3.7a0
  pyproject.toml
Labels: ready_to_eval, release

#411 Remove plan input todo
  portia/storage.py
Labels: ready_to_eval

#433 Small dogfooding improvements
  portia/__init__.py
  portia/portia.py
  portia/storage.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#435 Fix safelogger wrapper.
  portia/logger.py
Labels: ready_to_eval

#437 Release v0.3.8
  pyproject.toml
Labels: ready_to_eval, release

#438 Use backport typing @override for python < 3.12
  tests/utils.py
  uv.lock
Labels: ready_to_eval

#431 Execution hooks dogfooding
  portia/clarification.py
  portia/clarification_handler.py
  portia/execution_hooks.py
  portia/plan_run.py
  portia/portia.py
  tests/integration/test_e2e.py
  tests/unit/test_clarifications.py
  tests/unit/test_execution_hooks.py
  tests/unit/test_plan_run.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#432 Clarification source
  portia/clarification.py
  portia/execution_agents/clarification_tool.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_hooks.py
  portia/open_source_tools/browser_tool.py
  portia/open_source_tools/local_file_reader_tool.py
  portia/portia.py
  portia/tool.py
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_context.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/test_execution_utils.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/execution_agents/test_output.py
  tests/unit/open_source_tools/test_browser_tool.py
  tests/unit/test_clarification_handler.py
  tests/unit/test_clarifications.py
  tests/unit/test_cli_clarification_handler.py
  tests/unit/test_execution_hooks.py
  tests/unit/test_plan_run.py
  tests/unit/test_portia.py
  tests/utils.py
  uv.lock
Labels: ready_to_eval

#439 Sort execution agent email fussiness
  portia/execution_agents/default_execution_agent.py
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  tests/unit/execution_agents/test_default_execution_agent.py
Labels: ready_to_eval

#440 Small fixes
  portia/clarification.py
  portia/execution_agents/default_execution_agent.py
  portia/portia.py
  uv.lock
Labels: ready_to_eval

#404 [POR-1203] Browser tool structured output
  portia/open_source_tools/browser_tool.py
  tests/unit/open_source_tools/test_browser_tool.py
Labels: ready_to_eval

#434 [POR-1396] Add telemetry to SDK
  portia/common.py
  portia/execution_agents/base_execution_agent.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/one_shot_agent.py
  portia/portia.py
  portia/telemetry/__init__.py
  portia/telemetry/telemetry_service.py
  portia/telemetry/views.py
  pyproject.toml
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/telemetry/test_telemetry_service.py
  tests/unit/test_common.py
  tests/unit/test_portia.py
  uv.lock
Labels: ready_to_eval

#446 action fix
  .github/workflows/testing.yml
Labels: ready_to_eval

#450 llm structured tool
  portia/open_source_tools/llm_tool.py
  tests/unit/open_source_tools/test_llm_tool.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#447 Allow a default storage dir
  portia/config.py
  portia/portia.py
  tests/unit/test_config.py
Labels: ready_to_eval

#448 Add Redis caching for LLM calls
  .github/workflows/evals.yml
  portia/common.py
  portia/config.py
  portia/model.py
  pyproject.toml
  tests/integration/test_e2e.py
  tests/unit/test_config.py
  tests/unit/test_model.py
  tests/utils.py
  uv.lock
Labels: ready_to_eval, codex

#453 [POR-1392] Telemetry on
  portia/telemetry/telemetry_service.py
  tests/unit/telemetry/test_telemetry_service.py
Labels: ready_to_eval

#457 Fix 404s
  README.md
Labels: ready_to_eval

#458 Release v0.4.0
  pyproject.toml
Labels: ready_to_eval, release

#462 Planning prompt improvement
  portia/cli_clarification_handler.py
  portia/planning_agents/default_planning_agent.py
  portia/portia.py
Labels: ready_to_eval

#464 Fix example
  example.py
Labels: ready_to_eval

#469 Release 0.3.9 PR - Planning prompt fix for anthropic
  portia/cli_clarification_handler.py
  portia/execution_agents/default_execution_agent.py
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  pyproject.toml
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/utils.py
  uv.lock
Labels: ready_to_eval

#472 Fix README heading
  CONTRIBUTING.md
Labels: ready_to_eval

#470 Fix planner retry
  portia/templates/default_planning_agent.xml.jinja
  tests/unit/planning_agents/test_default_planning_agent.py
Labels: ready_to_eval

#473 Don't run before_step_execution after a clarification
  portia/portia.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#456 Allow passing task data to the browser tool
  portia/open_source_tools/browser_tool.py
  tests/unit/open_source_tools/test_browser_tool.py
Labels: ready_to_eval

#479 POR-1480: Streamable HTTP transport for MCP
  portia/mcp_session.py
  portia/tool_registry.py
  pyproject.toml
  tests/integration/mcp_server.py
  tests/integration/test_mcp_session.py
  tests/unit/test_tool_registry.py
  uv.lock
Labels: ready_to_eval

#461 Add caching dependencies to 'all' install group
  pyproject.toml
  uv.lock
Labels: ready_to_eval
