Repository portiaAI/portia-sdk-python, pull requests merged in 2025-08, with the labels that each got.

#633 Support additionalProperties and improve serialisation of pydantic objects
  portia/tool.py
  portia/tool_registry.py
  tests/unit/test_tool.py
  tests/unit/test_tool_registry.py
Labels: ready_to_eval

#638 Enable GPT-5
  portia/model.py
Labels: ready_to_eval

#643 Fix logging exceptions within Stripe demo
  portia/logger.py
  portia/portia.py
  tests/unit/test_logging.py
  uv.lock
Labels: ready_to_eval

#650 st announcement banner
  README.md
  assets/steelthread_banner.png
Labels: ready_to_eval

#651 Update README.md
  README.md
Labels: ready_to_eval

#652 removal of singleton
  portia/cloud.py
  portia/storage.py
  portia/tool.py
  portia/tool_registry.py
  tests/integration/test_portia_cloud.py
  tests/unit/test_portia.py
  tests/unit/test_tool.py
Labels: ready_to_eval

#653 Update pydantic
  pyproject.toml
  uv.lock
Labels: ready_to_eval

#657 Add an optional timeout for tool calls
  portia/mcp_session.py
  portia/tool.py
  portia/tool_registry.py
  tests/unit/test_tool.py
  uv.lock
Labels: ready_to_eval

#660 Update README.md
  README.md
Labels: ready_to_eval

#662 Fix the timeouts from the mcp client
  portia/tool.py
  tests/unit/test_tool.py
  tests/utils.py
Labels: ready_to_eval

#678 Example builder nits
  example_builder.py
Labels: ready_to_eval

#665 Add PlanBuilderV2 method for creating plans
  example_builder.py
  portia/__init__.py
  portia/builder/__init__.py
  portia/builder/conditionals.py
  portia/builder/plan_builder_v2.py
  portia/builder/plan_v2.py
  portia/builder/reference.py
  portia/builder/step_v2.py
  portia/clarification.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/execution_utils.py
  portia/execution_agents/one_shot_agent.py
  portia/plan.py
  portia/portia.py
  portia/tool_registry.py
  pyproject.toml
  tests/integration/test_e2e.py
  tests/integration/test_plan_v2.py
  tests/unit/builder/test_plan_builder_v2.py
  tests/unit/builder/test_plan_v2.py
  tests/unit/builder/test_reference.py
  tests/unit/builder/test_step_v2.py
  tests/unit/execution_agents/test_execution_utils.py
  tests/unit/test_portia.py
  tests/unit/test_portia_async.py
  tests/unit/test_storage_async.py
  tests/unit/test_tool_registry.py
Labels: codex

#679 Conditional evaluation agent - evaluate natural language conditions
  portia/builder/step_v2.py
  portia/execution_agents/conditional_evaluation_agent.py
  portia/portia.py
  pyproject.toml
Labels: ready_to_eval

#681 Add templating in string conditions
  portia/builder/step_v2.py
Labels: ready_to_eval

#680 Fix SDK import error
  pyproject.toml
  uv.lock
Labels: ready_to_eval

#685 PlanBuilderV2 - Nathan review follow-ups
  example_builder.py
  portia/builder/step_v2.py
  portia/portia.py
  tests/unit/builder/test_plan_v2.py
  tests/unit/builder/test_step_v2.py
  tests/unit/test_portia.py
  uv.lock
Labels: ready_to_eval

#691 Improve example
  data/earth-whispers/poem.txt
  data/laser-sharks-ballad/poem.txt
  example.py
Labels: ready_to_eval

#687 Add integration tests for ConditionalEvaluationAgent
  portia/model.py
  pyproject.toml
  tests/integration/test_conditional_evaluation_agent.py
Labels: ready_to_eval, codex

#723 [Issue#717] Fix LLMTool to expect dict as well
  portia/open_source_tools/llm_tool.py
  tests/unit/open_source_tools/test_llm_tool.py
Labels: ready_to_eval

#725 Ensure step outputs can be referenced correctly
  portia/builder/reference.py
  portia/portia.py
  tests/unit/builder/test_reference.py
  tests/unit/builder/test_step_v2.py
Labels: ready_to_eval

#721 Add tests for PlanV2
  .github/workflows/testing.yml
  portia/builder/step_v2.py
  portia/portia.py
  tests/integration/test_plan_v2.py
  tests/unit/builder/test_step_v2.py
  tests/unit/test_portia.py
  tests/unit/test_portia_plan_v2.py
Labels: ready_to_eval

#727 Ensure tool calls are displayed in UI (+ unify FunctionStep and InvokeToolStep under the hood)
  portia/__init__.py
  portia/builder/plan_builder_v2.py
  portia/builder/step_v2.py
  portia/model.py
  portia/portia.py
  portia/tool.py
  portia/tool_decorator.py
  tests/unit/builder/test_plan_builder_v2.py
  tests/unit/builder/test_step_v2.py
  tests/unit/test_tool_decorator.py
  tests/unit/test_tool_decorator_async.py
Labels: ready_to_eval

#736 Add Contributors section to README
  README.md
Labels: ready_to_eval

#741 Update names
  README.md
Labels: ready_to_eval
