Repository portiaAI/portia-sdk-python, pull requests merged in 2025-04, with the labels that each got.

#271 Fixed the step summarizer to include tool's description in context
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/one_shot_agent.py
  portia/execution_agents/utils/step_summarizer.py
  pyproject.toml
  tests/unit/execution_agents/utils/test_step_summarizer.py
Labels: ready_to_eval

#272 Nicer Print Summaries.
  portia/cli.py
  portia/plan.py
  tests/unit/test_plan.py
Labels: ready_to_eval

#274 fix for double planning
  portia/cli.py
Labels: ready_to_eval

#275 Add pyright pre commit
  .pre-commit-config.yaml
Labels: ready_to_eval

#273 Remove LLMWrapper
  portia/_unstable/browser_tool.py
  portia/config.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/one_shot_agent.py
  portia/execution_agents/utils/final_output_summarizer.py
  portia/execution_agents/utils/step_summarizer.py
  portia/introspection_agents/default_introspection_agent.py
  portia/llm_wrapper.py
  portia/model.py
  portia/open_source_tools/image_understanding_tool.py
  portia/open_source_tools/llm_tool.py
  portia/planning_agents/default_planning_agent.py
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/utils/test_final_output_summarizer.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/open_source_tools/conftest.py
  tests/unit/open_source_tools/test_image_understanding_tool.py
  tests/unit/open_source_tools/test_llm_tool.py
  tests/unit/planning_agents/test_default_planning_agent.py
  tests/unit/test_config.py
  tests/unit/test_llm_wrapper.py
  tests/unit/test_portia.py
  tests/utils.py
Labels: ready_to_eval

#279 Bump MCP SDK to latest version
  poetry.lock
  pyproject.toml
Labels: ready_to_eval

#280 Handle refs, enums + defaults in schemas
  poetry.lock
  portia/templates/tool_description.xml.jinja
  portia/tool.py
  portia/tool_registry.py
  pyproject.toml
  tests/unit/test_tool.py
Labels: ready_to_eval

#286 Bring back LLMWrapper as deprecated and decoupled from everything
  portia/llm_wrapper.py
  tests/unit/test_llm_wrapper.py
Labels: ready_to_eval

#287 Add tracing to planner evals
  portia/model.py
Labels: ready_to_eval

#283 Change plans to generate steps with inputs only from prev outputs
  portia/execution_agents/context.py
  portia/plan.py
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  portia/templates/example_plans.py
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_context.py
  tests/unit/planning_agents/test_default_planning_agent.py
  tests/unit/test_plan.py
  tests/unit/test_plan_builder.py
  tests/unit/test_tool.py
  tests/utils.py
Labels: ready_to_eval

#270 Sort large outputs in agent memory
  .gitignore
  poetry.lock
  portia/__init__.py
  portia/cloud.py
  portia/config.py
  portia/execution_agents/base_execution_agent.py
  portia/execution_agents/context.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/execution_utils.py
  portia/execution_agents/one_shot_agent.py
  portia/execution_agents/output.py
  portia/execution_agents/utils/final_output_summarizer.py
  portia/execution_agents/utils/step_summarizer.py
  portia/plan.py
  portia/plan_run.py
  portia/portia.py
  portia/storage.py
  portia/tool.py
  portia/tool_wrapper.py
  pyproject.toml
  tests/integration/test_e2e.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_context.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/test_execution_utils.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/execution_agents/test_output.py
  tests/unit/execution_agents/utils/test_final_output_summarizer.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/test_config.py
  tests/unit/test_plan_run.py
  tests/unit/test_portia.py
  tests/unit/test_storage.py
  tests/unit/test_tool_wrapper.py
  tests/utils.py
Labels: ready_to_eval

#289 Include the output schema+description in the context
  portia/planning_agents/context.py
Labels: ready_to_eval

#285 [POR-1019] Add browserbase support to browser tool
  poetry.lock
  portia/_unstable/browser_tool.py
  pyproject.toml
Labels: ready_to_eval

#288 Try to fix flakey tests
  .github/workflows/evals.yml
  tests/integration/test_e2e.py
Labels: ready_to_eval

#290 Add more tweaks to planning prompt to reduce hallucinations
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
Labels: ready_to_eval

#284 fix for PAT
  .github/workflows/create-release-pr.yml
  .github/workflows/create-release-tag.yml
Labels: ready_to_eval

#294 Release v0.1.12
  pyproject.toml
Labels: release

#281 Refactor ToolRegistry to simplify code. Add model field to LLMTool, Image tool and browser tool
  portia/_unstable/browser_tool.py
  portia/config.py
  portia/open_source_tools/image_understanding_tool.py
  portia/open_source_tools/llm_tool.py
  portia/open_source_tools/registry.py
  portia/portia.py
  portia/tool.py
  portia/tool_registry.py
  tests/integration/test_e2e.py
  tests/integration/test_portia_cloud.py
  tests/integration/test_runner_context.py
  tests/unit/test_portia.py
  tests/unit/test_tool_registry.py
Labels: ready_to_eval

#265 [POR-1094] - Remove system context extensions
  portia/execution_agents/context.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_context.py
  portia/open_source_tools/image_understanding_tool.py
  portia/open_source_tools/llm_tool.py
  portia/planning_agents/base_planning_agent.py
  portia/planning_agents/context.py
  portia/planning_agents/default_planning_agent.py
  portia/portia.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_context.py
  tests/unit/open_source_tools/test_image_understanding_tool.py
  tests/unit/planning_agents/test_default_planning_agent.py
Labels: ready_to_eval

#301 Package python update
  poetry.lock
  pyproject.toml
Labels: ready_to_eval

#302 Python fix production
  poetry.lock
  pyproject.toml
Labels: ready_to_eval

#305 Rsa vulnerability fix
  poetry.lock
  pyproject.toml
Labels: ready_to_eval

#299 Pass temperature through for GoogleGenAIGenerativeModel
  portia/model.py
  tests/integration/test_model.py
Labels: ready_to_eval

#292 [Breaking Changes] Refactor Model configuration settings
  README.md
  poetry.lock
  portia/__init__.py
  portia/_unstable/browser_tool.py
  portia/common.py
  portia/config.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/one_shot_agent.py
  portia/execution_agents/utils/final_output_summarizer.py
  portia/introspection_agents/default_introspection_agent.py
  portia/llm_wrapper.py
  portia/model.py
  portia/open_source_tools/image_understanding_tool.py
  portia/open_source_tools/llm_tool.py
  portia/planning_agents/default_planning_agent.py
  pyproject.toml
  tests/integration/test_e2e.py
  tests/integration/test_model.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/utils/test_final_output_summarizer.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/open_source_tools/conftest.py
  tests/unit/planning_agents/test_default_planning_agent.py
  tests/unit/test_config.py
  tests/unit/test_llm_wrapper.py
  tests/unit/test_model.py
  tests/unit/test_portia.py
  tests/utils.py
Labels: ready_to_eval

#310 Browser tool local fix (needed before prod push)
  portia/_unstable/browser_tool.py
Labels: ready_to_eval

#304 User Led Learning: SDK similarity search
  portia/plan.py
  portia/storage.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#295 Ollama support
  .github/workflows/testing.yml
  poetry.lock
  portia/common.py
  portia/config.py
  portia/model.py
  pyproject.toml
  tests/integration/test_model.py
Labels: ready_to_eval

#314 Rename get_model to get_generative_model
  portia/_unstable/browser_tool.py
  portia/config.py
  portia/open_source_tools/image_understanding_tool.py
  portia/open_source_tools/llm_tool.py
  tests/unit/open_source_tools/conftest.py
  tests/unit/test_config.py
Labels: ready_to_eval

#312 Fix two flaky tests
  portia/planning_agents/default_planning_agent.py
  portia/templates/default_planning_agent.xml.jinja
  tests/integration/test_e2e.py
Labels: ready_to_eval

#315 example plans prompting
  .gitignore
  portia/planning_agents/context.py
  portia/storage.py
  portia/templates/default_planning_agent.xml.jinja
Labels: ready_to_eval

#316 Fix cli.py
  portia/cli.py
  portia/config.py
Labels: ready_to_eval

#318 Example planning biasing
  portia/templates/default_planning_agent.xml.jinja
Labels: ready_to_eval

#317 Improve CLI config for models and providers
  portia/cli.py
  portia/config.py
Labels: ready_to_eval

#320 Release v0.2.1
  pyproject.toml
Labels: ready_to_eval, release

#321 Fix create-release-tag script
  .github/workflows/create-release-tag.yml
Labels: ready_to_eval

#322 Add some basic CLI unittests
  portia/cli.py
  pyproject.toml
  tests/unit/test_cli.py
Labels: ready_to_eval

#327 Fix SDK evals for model name change
  .github/workflows/evals.yml
Labels: ready_to_eval

#326 Move CLI clarification handler to a separate file
  portia/clarification_handler.py
  portia/cli.py
  portia/cli_clarification_handler.py
  tests/unit/test_cli_clarification_handler.py
Labels: ready_to_eval

#328 [POR-1245] - Call save on plan_run
  portia/portia.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#325 Added running introspection agent evals
  .github/workflows/evals.yml
Labels: ready_to_eval

#319 Execution agent uses memory
  portia/execution_agents/base_execution_agent.py
  portia/execution_agents/context.py
  portia/execution_agents/default_execution_agent.py
  portia/execution_agents/execution_utils.py
  portia/execution_agents/one_shot_agent.py
  portia/portia.py
  portia/storage.py
  tests/unit/execution_agents/test_base_execution_agent.py
  tests/unit/execution_agents/test_context.py
  tests/unit/execution_agents/test_default_execution_agent.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/open_source_tools/conftest.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#330 ASYNC MCP support
  .github/workflows/evals.yml
  portia/tool_registry.py
  pyproject.toml
  tests/unit/test_tool_registry.py
Labels: ready_to_eval

#334 Update to use local rather than remote version of browser tool
  portia/open_source_tools/browser_tool.py
Labels: ready_to_eval

#337 Add extra argument to LLMTool `input_data: list[str]`
  portia/open_source_tools/llm_tool.py
  tests/unit/open_source_tools/test_llm_tool.py
Labels: ready_to_eval

#335 [POR-1242] Add variant of action clarification that requires user confirmation
  portia/clarification.py
  portia/cli_clarification_handler.py
  portia/open_source_tools/browser_tool.py
  tests/unit/open_source_tools/test_browser_tool.py
  tests/unit/test_cli_clarification_handler.py
Labels: ready_to_eval

#338 Browser tool prompts
  portia/open_source_tools/browser_tool.py
Labels: ready_to_eval

#341 Handle empty user id
  portia/portia.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#343 Release v0.3.0
  pyproject.toml
Labels: release

#345 Added e2e test for input/ouputs dependencies
  .github/workflows/evals.yml
  portia/templates/default_planning_agent.xml.jinja
  tests/integration/test_e2e.py
Labels: ready_to_eval

#346 Add logging for version and models used on startup
  portia/portia.py
Labels: ready_to_eval

#348 Introspection default model
  portia/config.py
  portia/portia.py
Labels: ready_to_eval

#347 Anthropic models: Increase max tokens and fall back on instructor for structured output
  portia/model.py
  tests/integration/test_e2e.py
  tests/unit/test_model.py
Labels: ready_to_eval

#353 Catch in logs
  portia/logger.py
Labels: ready_to_eval

#350 Fix tagging
  .github/workflows/create-release-tag.yml
Labels: ready_to_eval

#349 Browser use tabs
  portia/open_source_tools/browser_tool.py
  tests/unit/open_source_tools/test_browser_tool.py
Labels: ready_to_eval

#340 Do not show toolIDs in log output for plan
  portia/portia.py
Labels: ready_to_eval

#329 Introspection agent uses memory
  portia/introspection_agents/default_introspection_agent.py
  portia/introspection_agents/introspection_agent.py
  portia/portia.py
  portia/storage.py
  tests/integration/test_e2e.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/test_storage.py
Labels: ready_to_eval

#357 Handle JSONSchema omissible fields in pydantic model generation
  portia/portia.py
  portia/tool_registry.py
  tests/unit/test_tool_registry.py
Labels: ready_to_eval

#358 Return the saved user
  portia/storage.py
Labels: ready_to_eval

#356 Allow 4096 char descriptions + add test
  portia/tool.py
  tests/integration/test_execution_agent.py
  tests/unit/test_tool.py
Labels: ready_to_eval

#359 Release v0.3.1
  pyproject.toml
Labels: release

#351 Add PDF reader tool
  poetry.lock
  portia/common.py
  portia/open_source_tools/pdf_reader_tool.py
  portia/open_source_tools/registry.py
  pyproject.toml
  tests/unit/open_source_tools/test_pdf_reader_tool.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#361 Fix latest release tagging
  .github/workflows/create-release-tag.yml
Labels: ready_to_eval

#364 Update prompt for browser tool
  portia/open_source_tools/browser_tool.py
Labels: ready_to_eval

#366 Small memory update
  portia/storage.py
Labels: ready_to_eval

#365 Make sure if portia-cloud-replan fails we still exit with PlanError
  portia/portia.py
  tests/integration/test_e2e.py
Labels: ready_to_eval

#363 Support future ready contract
  portia/portia.py
  portia/tool.py
  portia/tool_wrapper.py
  tests/unit/test_portia.py
  tests/unit/test_tool.py
Labels: ready_to_eval

#362 [POR-1317] Added introspection agent prompt improvements
  portia/execution_agents/utils/final_output_summarizer.py
  portia/introspection_agents/default_introspection_agent.py
  portia/introspection_agents/introspection_agent.py
  portia/portia.py
  tests/unit/execution_agents/utils/test_final_output_summarizer.py
  tests/unit/introspection_agents/test_default_introspection_agent.py
  tests/unit/test_portia.py
Labels: ready_to_eval

#370 Added minor edit to prompt to force not using this complete condition for skip cases
  portia/introspection_agents/default_introspection_agent.py
Labels: ready_to_eval
