Repository portiaAI/portia-sdk-python, pull requests merged in 2025-06, with the labels that each got.

#471 [POR-1442] Fix parsing params for tools and update daily runs thresholds
  .github/workflows/evals.yml
  portia/common.py
  tests/unit/test_common.py
Labels: ready_to_eval

#483 Fix azure openai default model (to gpt-4.1)
  portia/config.py
Labels: ready_to_eval

#487 [POR-1481] - change google package
  pyproject.toml
  uv.lock
Labels: ready_to_eval

#490 Revert "[POR-1481] - change google package"
  pyproject.toml
  uv.lock
Labels: ready_to_eval

#497 Revert "Remove generics from tool def"
  portia/clarification.py
  portia/common.py
  portia/execution_agents/clarification_tool.py
  portia/execution_agents/output.py
  portia/open_source_tools/browser_tool.py
  portia/open_source_tools/calculator_tool.py
  portia/open_source_tools/image_understanding_tool.py
  portia/open_source_tools/llm_tool.py
  portia/open_source_tools/local_file_reader_tool.py
  portia/open_source_tools/local_file_writer_tool.py
  portia/open_source_tools/pdf_reader_tool.py
  portia/open_source_tools/search_tool.py
  portia/open_source_tools/weather.py
  portia/tool.py
Labels: ready_to_eval

#502 special handling for gemini lists
  portia/execution_agents/default_execution_agent.py
  tests/unit/execution_agents/test_default_execution_agent.py
Labels: ready_to_eval

#498 Add missing line break to README.
  README.md
Labels: ready_to_eval

#507 Fix tool clarification exec hook handling
  portia/execution_hooks.py
  tests/unit/test_execution_hooks.py
Labels: ready_to_eval

#452 step level structured output
  portia/execution_agents/base_execution_agent.py
  portia/execution_agents/utils/step_summarizer.py
  portia/plan.py
  portia/tool.py
  portia/tool_wrapper.py
  tests/unit/execution_agents/utils/test_step_summarizer.py
  tests/unit/test_tool.py
Labels: ready_to_eval

#505 Small Improvements from e2e
  portia/plan.py
  portia/planning_agents/default_planning_agent.py
Labels: ready_to_eval

#508 Release v0.4.2
  pyproject.toml
Labels: release

#509 Handle running MCP server better
  portia/execution_agents/context.py
  portia/plan.py
  portia/templates/default_planning_agent.xml.jinja
  portia/tool_registry.py
  pyproject.toml
  tests/unit/execution_agents/test_context.py
  tests/unit/planning_agents/test_default_planning_agent.py
  uv.lock
Labels: ready_to_eval

#514 Update pyproject.toml after cherry pick
  pyproject.toml
Labels: ready_to_eval

#515 improve description
  portia/plan.py
Labels: ready_to_eval

#517 Support Google 2.5
  portia/config.py
  tests/unit/test_config.py
  uv.lock
Labels: ready_to_eval

#521 Fix bug in omissible fields handling where multiple tools can impact one another
  portia/tool_registry.py
  tests/unit/test_tool_registry.py
Labels: ready_to_eval

#526 Fix CLI tool list serialisation error and improve descriptions
  portia/cli.py
  portia/templates/tool_description.xml.jinja
  portia/tool.py
Labels: ready_to_eval

#519 Add feature tool decorator
  .github/workflows/ruff.yml
  portia/__init__.py
  portia/tool_decorator.py
  tests/unit/test_tool_decorator.py
Labels: ready_to_eval

#532 Release v0.4.4
  pyproject.toml
Labels: ready_to_eval, release

#534 Release v0.4.5
  pyproject.toml
Labels: ready_to_eval, release

#535 clarifications enabled feature flag removal
  .github/workflows/evals.yml
  portia/config.py
  portia/execution_agents/one_shot_agent.py
  portia/telemetry/telemetry_service.py
  tests/unit/execution_agents/test_oneshot_agent.py
  tests/unit/test_tool_decorator.py
  uv.lock
Labels: ready_to_eval

#537 Fix tool registry for remote tools
  portia/tool_registry.py
Labels: ready_to_eval

#539 Improve timeout handling to handle SSE issues
  portia/tool_registry.py
  tests/unit/test_tool_registry.py
  uv.lock
Labels: ready_to_eval

#541 Release v0.4.6
  pyproject.toml
Labels: release

#546 Update instructor version
  portia/telemetry/telemetry_service.py
  pyproject.toml
  tests/unit/open_source_tools/test_browser_tool.py
  tests/unit/telemetry/test_telemetry_service.py
  tests/unit/test_model.py
  tests/unit/test_tool.py
  uv.lock
Labels: ready_to_eval
